name: Deploy

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Authenticate gcloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/253413868906/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@vaulted-anthem-354102.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Login to Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/a2go/slides:latest
            us-central1-docker.pkg.dev/vaulted-anthem-354102/slides/slides:latest
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: us-central1-docker.pkg.dev/vaulted-anthem-354102/slides/slides:latest
          service: slides
